version: '2'
services:
    repfsw-haproxy1:
        image: haproxy:1.7.9-alpine
        container_name: repfsw-haproxy1
        environment:
          - NAME=svr_repfsw-haproxy1
        volumes:
            - /fssvc/haproxy/1.7.9-alpine/conf:/usr/local/etc/haproxy
        ports:
            - "80:80"
            - "443:443"
        expose:
          - "80"
          - "443"
        networks:
           - fsw-red
networks:
      fsw-red:
          external: true