version: '2'
services:
    repfsw-nexus1:
        image: sonatype/nexus3:3.6.1
        container_name: repfsw-nexus1
        environment:
          - NAME=svr_repfsw_nexus1
          - NEXUS_CONTEXT=nexus3
        volumes:
          - /fssvc/nexus/3.6.1/data:/nexus-data
        ports:
            - "8081:8081"
        expose:
          - "8081"
        networks:
           - fsw-red
networks:
      fsw-red:
          external: true