version: '2'
services:
    sonarqube:
        image: sonarqube:6.7-alpine
        environment:
          - SONARQUBE_JDBC_URL=jdbc:oracle:thin:@192.168.30.40:1521/devops
        volumes:
          - /fssvc/sonarqube/6.7-alpine/conf:/opt/sonarqube/conf
          - /fssvc/sonarqube/6.7-alpine/data:/opt/sonarqube/data
          - /fssvc/sonarqube/6.7-alpine/extensions:/opt/sonarqube/extensions
          - /fssvc/sonarqube/6.7-alpine/bundle-plugins:/opt/sonarqube/lib/bundled-plugins
        ports:
            - "9000:9000"
            - "9092:9092"
        networks:
           - fsw-red
networks:
      fsw-red:
          external: true