version: '2'
services:
    cidfsw-haproxy1:
        image: haproxy:1.7.9-alpine
        container_name: cidfsw-haproxy1
        environment:
          - NAME=name_cidfsw-haproxy1
        volumes:
            - /fssvc/haproxy/1.7.9-alpine/conf:/usr/local/etc/haproxy
        ports:
            - "80:80"
            - "443:443"
        expose:
            - "80"
            - "443"
        networks:
           - fsw-red
networks:
      fsw-red:
          external: true