version: '2'
services:
    nexus:
        image: sonatype/nexus3:3.6.1
        volumes:
          - /fssvc/nexus/3.6.1/data:/nexus-data
        ports:
            - "8081:8081"
        networks:
           - fsw-red
networks:
      fsw-red:
          external: true